var group multierror.Group

for _, name := range names {
	name := name
	group.Go(func() error {
		return db.CreateUser(name)
	})
}

if err := group.Wait(); err != nil {
	for _, e := range err.Errors {
		// 個々の並行処理に対するエラー処理
	}
}